#!/usr/bin/env bash
# Maintainer: joekamprad [joekamprad //a_t// endeavouros.com]
git clone https://github.com/endeavouros-team/endeavouros-i3wm-setup.git
cd endeavouros-i3wm-setup/etc/skel/
cp -R .config ~/                                            
chmod -R +x ~/.config/i3/scripts
cp .Xresources .profile set_once.sh xed.dconf ~/
cd ..
rm -rf endeavouros-i3wm-setup
sed -i 's|\(exec --no-startup-id ~/set_once.sh\)|# \1|' ~/.config/i3/config
#wget https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-packages-lists/master/i3
#sudo pacman -S --needed - < i3
eos-packagelist --install "i3-Window-Manager"
