#!/usr/bin/env bash
# Maintainer: joekamprad [joekamprad //a_t// endeavouros.com]
username="$1"
git clone -b kde https://github.com/endeavouros-team/endeavouros-i3wm-setup.git
cd endeavouros-i3wm-setup/etc/skel/
cp -R .config /home/$username/
cp xed.dconf /home/$username/
cd ..
rm -rf endeavouros-i3wm-setup
chown -R $username:$username /home/$username
su $username
cd /home/$username/
dbus-launch dconf load / < /home/$username/xed.dconf
chmod -R +x /home/$username/.config/i3/scripts
wget https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-packages-lists/master/i3
sudo pacman -S --needed --noconfirm - < /home/$username/i3
rm /home/$username/i3
#eos-packagelist --install "i3-Window-Manager"
