#!/usr/bin/env bash
# Maintainer: joekamprad [joekamprad //a_t// endeavouros.com]
username="$1"
git clone https://github.com/endeavouros-team/endeavouros-i3wm-setup.git
cd endeavouros-i3wm-setup/etc/skel/
cp -R .config /home/$username/
cp .Xresources .profile set_once.sh xed.dconf /home/$username/
cd ..
rm -rf endeavouros-i3wm-setup
chown -R $username:$username /home/$username
chmod -R +x /home/$username/.config/i3/scripts
chmod +x /home/$username/set_once.sh
wget https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-packages-lists/master/i3
pacman -S --needed --noconfirm - < i3
rm i3
systemctl enable lightdm
