#!/usr/bin/env bash
grep -v "|#|" -h endeavouros-i3wm-setup/.config/i3/keybindings | 
	column -t -s"~" -c 90 -N Name,Key,Action |
	rofi\
		-font "dejavu sans mono 10"\
 		-width 80\
 		-location 2\
 		-dmenu\
 		-i\
 		-p 'Cheat-Cuts'\
 		-hide-scrollbar

