#!/usr/bin/env bash

# Simple power-profiles-daemon switcher using rofi and static theme, with notification
#
# Copyright (C) 2025 Johannes Kamprad
#
# SPDX-License-Identifier: GPL-3.0-or-later

# needs rofi config:
# $HOME/.config/rofi/powermenu.rasi

ROFI_THEME="${HOME}/.config/rofi/power-profiles.rasi"
declare -A TAGS
TAGS=(
  [cancel]="<span foreground='red'></span>  Cancel"
  [performance]="<span foreground='yellow'></span>  Performance"
  [balanced]="<span foreground='lightblue'></span>  Balanced"
  [power-saver]="<span foreground='green'></span>  Power Saver"
)

# Dependency checks
command -v powerprofilesctl >/dev/null 2>&1 || { echo "powerprofilesctl not found"; exit 1; }
command -v rofi >/dev/null 2>&1 || { echo "rofi not found"; exit 1; }
if ! command -v notify-send >/dev/null 2>&1; then
  notify_send_missing=true
fi

current_profile="$(powerprofilesctl get 2>/dev/null)"
ROFI_ARGS=(-dmenu -i -theme "$ROFI_THEME" -p "Change Profile" -mesg "<b>Current used:</b> &#x0a;${TAGS[$current_profile]}" -markup-rows)

# if not invoked by click return current option
if [[ ! $button ]]; then
  echo "${TAGS[$current_profile]}"
  exit 0
fi

# Menu entries
# sets cancel to be on top
options="${TAGS[cancel]}"

if powerprofilesctl list | grep -q "performance"; then
  options="$options\n${TAGS[performance]}"
fi
if powerprofilesctl list | grep -q "balanced"; then
  options="$options\n${TAGS[balanced]}"
fi
if powerprofilesctl list | grep -q "power-saver"; then
  options="$options\n${TAGS[power-saver]}"
fi

# Show menu
chosen="$(echo -e "$options" | rofi "${ROFI_ARGS[@]}")"

# Run selection
case $chosen in
    "${TAGS[performance]}")
        powerprofilesctl set performance
        ;;
    "${TAGS[balanced]}")
        powerprofilesctl set balanced
        ;;
    "${TAGS[power-saver]}")
        powerprofilesctl set power-saver
        ;;
    "${TAGS[cancel]}"|"")
        echo "${TAGS[$current_profile]}"
        exit 0
        ;;
esac


# Send notification if available and update block
if [[ "$chosen" != "${TAGS[cancel]}" && -z "${notify_send_missing}" ]]; then
  notify-send -i dialog-information "Power Profile Changed" "New profile: ${chosen}"
  echo "$chosen"
fi

