#!/usr/bin/env bash
grep -v "|#|" -h ~/.config/i3/keybindings-rofi | 
	column -t -s"~" -c 90 -N Name,Key,Action |
	rofi\
		-font "dejavu sans mono 10"\
 		-width 80\
 		-location 2\
 		-dmenu\
 		-i\
 		-p 'i3-Shortcuts'\
 		-hide-scrollbar

